The old Linux version is 2.1.132
Signed-off-by: Eric Zhou <zhoubb.eric@gmail.com>

diff --git a/scripts/Menuconfig b/scripts/Menuconfig
--- a/scripts/Menuconfig
+++ b/scripts/Menuconfig
@@ -19,17 +19,41 @@
 # Portions of this script were borrowed from the original Configure
 # script.
 #
-# Please send comments / questions / bug fixes to roadcapw@titus.org
+# William Roadcap was the original author of Menuconfig.
+# Michael Elizabeth Chastain (mec@shout.net) is the current maintainer.
 #
-# 070498 Stepan Kasal <kasal@math.cas.cz> - one change borrowed
-# from 2.1.x version:
-#     131197 Michael Chastain (mec@shout.net) - output all lines for a
-#     choice list, not just the selected one.  This makes the output
-#     the same as Configure output, which is important for smart config
-#     dependencies.
-# It also fixes the bug when menuconfig sets CONFIG_M386=y every time
-# it is ran.
-#----------------------------------------------------------------------------
+# 070497 Bernhard Kaindl (bkaindl@netway.at) - get default values for
+# new bool, tristate and dep_tristate parameters from the defconfig file.
+# new configuration parameters are marked with '(NEW)' as in make config.
+#
+# 180697 Bernhard Kaindl (bkaindl@netway.at) - added the needed support
+# for string options. They are handled like the int and hex options.
+#
+# 081297 Pavel Machek (pavel@atrey.karlin.mff.cuni.cz) - better error 
+# handling
+#
+# 131197 Michael Chastain (mec@shout.net) - output all lines for a
+# choice list, not just the selected one.  This makes the output
+# the same as Configure output, which is important for smart config
+# dependencies.
+#
+# 101297 Michael Chastain (mec@shout.net) - remove sound driver cruft.
+#
+# 221297 Michael Chastain (mec@shout.net) - make define_bool actually
+# define its arguments so that later tests on them work right.
+#
+# 160198 Michael Chastain (mec@shout.net) - fix bug with 'c' command
+# (complement existing value) when used on virgin uninitialized variables.
+#
+# 090398 Axel Boldt (boldt@math.ucsb.edu) - allow for empty lines in help
+# texts.
+
+
+#
+# Change this to TRUE if you prefer all kernel options listed
+# in a single menu rather than the standard menu hierarchy.
+#
+single_menu_mode=
 
 #
 # Make sure we're really running bash.
@@ -41,14 +65,21 @@
 #
 set -h +o posix
 
+#
+# Converts "# xxx is not..." to xxx=n
+#
+parse_config () {
+	sed -e 's/# \(.*\) is not.*/\1=n/'
+}
 
 #
-# If you prefer all kernel options listed in a single menu rather than
-# the standard menu hierarchy, set SINGLE_MENU_MODE to "TRUE" in your
-# environment.
+# Parses the defconfig file to set the default for a new parameter.
 #
-single_menu_mode="${SINGLE_MENU_MODE:-FALSE}"
-
+function get_def () {
+	parse_config < arch/$ARCH/defconfig | grep "^$1=" > /tmp/conf.$$
+	. /tmp/conf.$$
+	rm /tmp/conf.$$
+}
 
 #
 # Load the functions used by the config.in files.
@@ -60,6 +91,19 @@ single_menu_mode="${SINGLE_MENU_MODE:-FALSE}"
 # Thank the heavens bash supports nesting function definitions.
 #
 load_functions () {
+
+#
+# Macro for setting the x and info varibles. get's default from defconfig
+# file if it's a new parameter.
+#
+function set_x () {
+	eval x=\$$1
+	if [ -z "$x" ]; then
+		get_def "$1"
+		eval x=\${$1:-'n'} INFO_$1="' (NEW)'"
+	fi
+	eval info="\$INFO_$1"
+}
 
 #
 # Additional comments
@@ -77,26 +121,18 @@ function define_bool () {
 }
 
 #
-# Define an int to a specific value.
-#
-
-function define_int () {
-	eval $1=$2
-}
-
-#
 # Create a boolean (Yes/No) function for our current menu
 # which calls our local bool function.
 #
 function bool () {
-	eval $2=\${$2:-'n'}  x=\$$2
+	set_x "$2"
 
 	case $x in
 	y|m)	flag="*" ;;
 	n)	flag=" " ;;
 	esac
 
-	echo -ne "'$2' '[$flag] $1' " >>MCmenu
+	echo -ne "'$2' '[$flag] $1$info' " >>MCmenu
 
 	echo -e "function $2 () { l_bool '$2' \"\$1\" ;}\n" >>MCradiolists
 }
@@ -112,7 +148,7 @@ function tristate () {
 	then
 		bool "$1" "$2"
 	else
-		eval $2=\${$2:-'n'}  x=\$$2
+		set_x "$2"
 	
 		case $x in
 		y) flag="*" ;;
@@ -120,7 +156,7 @@ function tristate () {
 		*) flag=" " ;;
 		esac
 	
-		echo -ne "'$2' '<$flag> $1' " >>MCmenu
+		echo -ne "'$2' '<$flag> $1$info' " >>MCmenu
 	
 		echo -e "
 		function $2 () { l_tristate '$2' \"\$1\" ;}" >>MCradiolists
@@ -165,7 +201,7 @@ function int () {
 }
 
 #
-# Add a menu item which will call our local int function.
+# Add a menu item which will call our local hex function.
 # 
 function hex () {
 	eval $2=\${$2:-"$3"} x=\${$2##*[x,X]}
@@ -173,6 +209,17 @@ function hex () {
 	echo -ne "'$2' '($x) $1' " >>MCmenu
 
 	echo -e "function $2 () { l_hex '$1' '$2' '$3' '$x' ;}" >>MCradiolists
+}
+
+#
+# Add a menu item which will call our local string function.
+# 
+function string () {
+	eval $2=\${$2:-"$3"} x=\$$2
+
+	echo -ne "'$2' '     $1: \"$x\"' " >>MCmenu
+
+	echo -e "function $2 () { l_string '$1' '$2' '$3' '$x' ;}" >>MCradiolists
 }
 
 #
@@ -233,9 +280,11 @@ function extract_help () {
      var=$(echo "$1"|sed 's/[][\/.^$*]/\\&/g')
      #now pick out the right help text:
      text=$(sed -n "/^$var[ 	]*\$/,\${
-                        /^$var[ 	]*\$/d
-                        /^#.*/d
-			/^[ 	]*\$/q
+                        /^$var[ 	]*\$/c\\
+${var}:\\
+
+                        /^#/b
+                        /^[^ 	]/q
                         s/^  //
                         p
                     }" Documentation/Configure.help)
@@ -297,23 +346,6 @@ function submenu () {
 }
 
 #
-# Create a menu entry to handle the traditional sound configuration.
-#
-function soundcfg () {
-	echo -ne "'l_soundcfg' "\
-		 "'Old configuration script "\
-		 "(For: SM Wave, PSS & AudioTrix Pro) -->' " >>MCmenu
-}
-
-#
-# Startup the traditional sound configuration program.
-#
-function l_soundcfg () {
-	clear
-	$MAKE -C drivers/sound config
-}
-
-#
 # Handle a boolean (Yes/No) option.
 #
 function l_bool () {
@@ -325,6 +357,7 @@ function l_bool () {
 		   	case $x in
 		   	y) eval $1=n ;;
 		   	n) eval $1=y ;;
+			*) eval $1=y ;;
 		   	esac ;;
 		*)	eval $1=n ;;
 		esac
@@ -337,14 +370,14 @@ function l_bool () {
 # Same as bool() except options are (Module/No)
 #
 function mod_bool () {
-	eval $2=\${$2:-'n'}  x=\$$2
+	set_x "$2"
 
 	case $x in
 	y|m) flag='M' ;;
 	*)   flag=' ' ;;
 	esac
 
-	echo -ne "'$2' '<$flag> $1' " >>MCmenu
+	echo -ne "'$2' '<$flag> $1$info' " >>MCmenu
 
 	echo -e "function $2 () { l_mod_bool '$2' \"\$1\" ;}" >>MCradiolists
 }
@@ -368,6 +401,7 @@ As a result, this feature will be built as a module." 4 70
 			case $x in
 			m) eval $1=n ;;
 			n) eval $1=m ;;
+			*) eval $1=m ;;
 			esac ;;
 		*)	eval $1=n ;;
 		esac
@@ -392,6 +426,7 @@ function l_tristate () {
 		   y) eval $1=n ;;
 		   n) eval $1=m ;;
 		   m) eval $1=y ;;
+		   *) eval $1=y ;;
 		   esac ;;
 		*) eval $1=n ;;
 		esac
@@ -414,7 +449,8 @@ function l_int () {
 			answer="`cat MCdialog.out`"
 			answer="${answer:-$3}"
 
-			# Avoid problems with GNU vs POSIX expr semantics.
+			# Semantics of + and ? in GNU expr changed, so
+			# we avoid them:
 			if expr "$answer" : '0$\|-[1-9][0-9]*$\|[1-9][0-9]*$' >/dev/null
 			then
 				eval $2="$answer"
@@ -448,7 +484,6 @@ function l_hex () {
 			answer="${answer:-$3}"
 			answer="${answer##*[x,X]}"
 
-			# Avoid problems with GNU vs POSIX expr semantics.
 			if expr "$answer" : '[0-9a-fA-F][0-9a-fA-F]*$' >/dev/null
 			then
 				eval $2="$answer"
@@ -466,6 +501,34 @@ function l_hex () {
 		help "$2" "$1"
 	done
 }
+
+#
+# Create a dialog for entering a string into a kernel option.
+#
+function l_string () {
+	while true
+	do
+		if $DIALOG --title "$1" \
+			--backtitle "$backtitle" \
+			--inputbox "$inputbox_instructions_string" \
+			10 75 "$4" 2>MCdialog.out
+		then
+			answer="`cat MCdialog.out`"
+			answer="${answer:-$3}"
+
+			#
+			# Someone may add a nice check for the entered
+			# string here...
+			#
+			eval $2=\"$answer\"
+
+			break
+		fi
+
+		help "$2" "$1"
+	done
+}
+
 
 #
 # Handle a one-of-many choice list.
@@ -526,12 +589,18 @@ function l_choice () {
 	done
 }
 
+#
+# Call awk, and watch for error codes, etc.
+#
+function callawk () {
+awk "$1" || echo "Awk died with error code $?. Giving up." || exit 1
+}
 
 #
 # A faster awk based recursive parser. (I hope)
 #
 function parser1 () {
-awk '
+callawk '
 BEGIN {
 	menu_no = 0
 	comment_is_option = 0
@@ -566,11 +635,6 @@ function parser(ifile,menu) {
 			printf("") >>menu
 		}
 		else if ($1 == "source") {
-			# Yuk!  Blah!  Phooey!
-			if ($2 ~ "drivers/sound") {
-				printf("soundcfg\n") >>menu
-			}
-
 			parser($2,menu)
 		}
 		else {
@@ -584,7 +648,7 @@ function parser(ifile,menu) {
 # Secondary parser for single menu mode.
 #
 function parser2 () {
-awk '
+callawk '
 BEGIN {
 	parser("'$CONFIG_IN'","MCmenu0")
 }
@@ -595,13 +659,10 @@ function parser(ifile,menu) {
 		if ($1 ~ /mainmenu_option|endmenu/) {
 			printf("") >>menu
 		} 
-		else if ($0 ~ /^#|\$MAKE|mainmenu_name/) {
+		else if ($0 ~ /^#|$MAKE|mainmenu_name/) {
 			printf("") >>menu
 		}
 		else if ($1 == "source") {
-			if ($2 ~ "drivers/sound") {
-				printf("soundcfg\n") >>menu
-			}
 			parser($2,menu)
 		}
 		else {
@@ -643,9 +704,9 @@ function parse_config_files () {
 	#
 	for i in MCmenu*
 	do
+		echo -n "."
 		source ./$i
 	done
-
 	rm -f MCmenu*
 }
 
@@ -667,13 +728,11 @@ function activate_menu () {
 		then
 			clear
 			cat <<EOM
-
 Menuconfig has encountered a possible error in one of the kernel's
 configuration files and is unable to continue.
 
-Please report this to the author <roadcapw@titus.org>.  You may also
-send a problem report to linux-kernel@vger.kernel.org or post a
-message to the linux.dev.kernel news group.
+Please report this to the maintainer <mec@shout.net>.  You may also
+send a problem report to <linux-kernel@vger.rutgers.edu>.
 
 Please indicate the kernel version you are trying to configure and
 which menu you were trying to enter when this error occurred.
@@ -719,7 +778,6 @@ EOM
 			stty sane
 			clear
 			cat <<EOM
-
 There seems to be a problem with the lxdialog companion utility which is
 built prior to running Menuconfig.  Usually this is an indicator that you
 have upgraded/downgraded your ncurses libraries and did not remove the 
@@ -734,8 +792,8 @@ the /usr/src/linux/scripts/lxdialog directory and issuing the
 "make clean all" command.
 
 If you have verified that your ncurses install is correct, you may email
-the author <roadcapw@titus.org> or post a message on the linux.dev.kernel
-news group for additional assistance. 
+the maintainer <mec@shout.net> or post a message to
+<linux-kernel@vger.rutgers.edu> for additional assistance. 
 
 EOM
 			cleanup
@@ -762,7 +820,7 @@ get_alt_config () {
 
 	while true
 	do
-		ALT_CONFIG="${ALT_CONFIG:-$_CONFIG}"
+		ALT_CONFIG="${ALT_CONFIG:-$DEFAULTS}"
 
 		$DIALOG --backtitle "$backtitle" \
 			--inputbox "\
@@ -828,7 +886,6 @@ save_alt_config () {
 			
 	while true
 	do
-
 		$DIALOG --backtitle "$backtitle" \
 			--inputbox "\
 Enter a filename to which this configuration should be saved \
@@ -875,25 +932,38 @@ EOM
 	rm -f help.out MCdialog.out
 }
 
-
 #
-# Load config file into the environment converting all
-# "# OPTION is not set" lines to "OPTION=n".
-#
-# The $ARCH defaults are loaded first so "new"/previously 
-# unconfigured parameters are assigned the proper defaults.
+# Load config options from a file.
+# Converts all "# OPTION is not set" lines to "OPTION=n" lines
 #
 function load_config_file () {
-	eval "`sed -e 's/# \(.*\) is not set.*/\1=n/' arch/$ARCH/defconfig $1`"
-}
+	awk '
+	  /# .* is not set.*/ { printf("%s=n\n", $2) }
+	! /# .* is not set.*/ { print }
+	' $1 >.tmpconfig
 
+	source ./.tmpconfig
+	rm -f .tmpconfig
+}
 
 #
 # Just what it says.
 #
 save_configuration () {
-	${DIALOG} --backtitle "$backtitle" \
-		  --infobox "Saving your kernel configuration..."  3 40
+        echo
+	echo -n "Saving your kernel configuration."
+
+	#
+	# Macro for setting the newval varible. get's default from defconfig
+	# file if it's a new parameter and it has not been shown yet.
+	#
+	function set_newval () {
+		eval newval=\$$1
+		if [ -z "$newval" ]; then
+			get_def "$1"
+			eval newval=\${$1:-'n'}
+		fi
+	}
 
 	#
 	# Now, let's redefine the configuration functions for final
@@ -902,25 +972,27 @@ save_configuration () {
 	# Nested function definitions, YIPEE!
 	#
 	function bool () {
-		eval define_bool "$2" "\${$2:-n}"
+		set_newval "$2"
+		eval define_bool "$2" "$newval"
 	}
 
 	function tristate () {
-		eval define_bool "$2" "\${$2:-n}"
+		set_newval "$2"
+		eval define_bool "$2" "$newval"
 	}
 
 	function dep_tristate () {
-		eval x=\${$2:-n}
+		set_newval "$2"
 
 		if eval [ "_$3" = "_m" ]
 		then
-			if [ "$x" = "y" ]
+			if [ "$newval" = "y" ]
 			then
-				x="m"
+				newval="m"
 			fi
 		fi
 
-		define_bool "$2" "$x"
+		define_bool "$2" "$newval"
 	}
 
 	function int () {
@@ -933,6 +1005,12 @@ save_configuration () {
 		eval x=\${$2:-"$3"}
 		echo "$2=$x" 			 >>$CONFIG
 		echo "#define $2 0x${x##*[x,X]}" >>$CONFIG_H
+	}
+
+	function string () {
+		eval x=\${$2:-"$3"}
+		echo "$2=\"$x\"" 			 >>$CONFIG
+		echo "#define $2 \"$x\""	>>$CONFIG_H
 	}
 
 	function define_bool () {
@@ -962,13 +1040,6 @@ save_configuration () {
                 	;;
         	esac
 	}
-
-	function define_int () {
-		eval $1="$2"
-		echo "$1=$2" >>$CONFIG
-		echo "#define $1 $2" >>$CONFIG_H
-	}
-
 
 	function choice () {
 		#
@@ -1038,8 +1109,10 @@ save_configuration () {
 		fi
 	}
 
-	DEF_CONFIG="${1:-$_CONFIG}"
-	DEF_CONFIG_H="$AUTOCONF_H"
+	echo -n "."
+
+	DEF_CONFIG="${1:-.config}"
+	DEF_CONFIG_H="include/linux/autoconf.h"
 
 	CONFIG=.tmpconfig
 	CONFIG_H=.tmpconfig.h
@@ -1051,28 +1124,13 @@ save_configuration () {
 	echo "/*" >$CONFIG_H
 	echo " * Automatically generated by make menuconfig: don't edit" >>$CONFIG_H
 	echo " */" >>$CONFIG_H
+	echo "#define AUTOCONF_INCLUDED" >> $CONFIG_H
 
-	MAKE=:	#To prevent sound Makefile from running.
-	
+	echo -n "."
 	if . $CONFIG_IN >>.menuconfig.log 2>&1
 	then
-		#
-		# Skip these steps if we are saving to an
-		# alternate configuration file.
-		#
-		if [ "$DEF_CONFIG" = "$_CONFIG" ]
+		if [ "$DEF_CONFIG" = ".config" ]
 		then
-			#
-			# Create the sound driver's config files for cards
-			# Which are compatible with the new config method.
-			#
-			if [ "_$CONFIG_TRIX"   != "_y" -a\
-			     "_$CONFIG_PSS"    != "_y" -a\
-			     "_$CONFIG_SMWAVE" != "_y"   ]
-			then
-				make -C drivers/sound kernelconfig >>.menuconfig.log 2>&1
-			fi
-
 			mv $CONFIG_H $DEF_CONFIG_H
 		fi
 
@@ -1090,14 +1148,12 @@ save_configuration () {
 	fi
 }
 
-
 #
 # Remove temporary files
 #
 cleanup () {
 	cleanup1
 	cleanup2
-	stty $S_TERMIO
 }
 
 cleanup1 () {
@@ -1130,7 +1186,6 @@ set_geometry () {
 	ROWS=$((ROWS-4))  COLS=$((COLS-5))
 }
 
-S_TERMIO=`stty -g`
 
 set_geometry `stty size 2>/dev/null`
 
@@ -1157,79 +1212,69 @@ inputbox_instructions_hex="\
 Please enter a hexadecimal value. \
 Use the <TAB> key to move from the input field to the buttons below it."
 
-DIALOG="${DIALOG:-./scripts/lxdialog/lxdialog}"
+inputbox_instructions_string="\
+Please enter a string value. \
+Use the <TAB> key to move from the input field to the buttons below it."
+
+DIALOG="./scripts/lxdialog/lxdialog"
 
 kernel_version="${VERSION}.${PATCHLEVEL}.${SUBLEVEL}"
 
 backtitle="Linux Kernel v$kernel_version Configuration"
 
-trap "cleanup ; rm -f .menuconfig ; exit 1" 1 2 15
+trap "cleanup ; exit 1" 1 2 15
 
 
 #
 # Locate default files.
 #
-DEFAULTS="arch/$ARCH/defconfig"
-
-CONFIG_IN="${1:-./config.in}"
-
-_CONFIG="${2:-.config}"
-
-if [ -f "$_CONFIG" ]; then
-  DEFAULTS=$_CONFIG
+CONFIG_IN=./config.in
+if [ "$1" != "" ] ; then
+	CONFIG_IN=$1
 fi
 
-AUTOCONF_H="${3:-include/linux/autoconf.h}"
+DEFAULTS=arch/$ARCH/defconfig
+if [ -f .config ]; then
+  DEFAULTS=.config
+fi
 
 if [ -f $DEFAULTS ]
 then
-  echo
   echo "Using defaults found in" $DEFAULTS
   load_config_file $DEFAULTS
 else
-  echo
   echo "No defaults found"
 fi
+
 
 # Fresh new log.
 >.menuconfig.log
 
-$DIALOG	--backtitle "$backtitle" \
-	--infobox "Preparing configuration scripts..." 3 40
-
-#
-# Check kernel version of previous menuconfig build.
-# If it's different then we should tell the sound driver
-# to rebuild its Config.in file.
-#
-rebuildsound=TRUE
-if [ -e .menuconfig ]
-then
-	read x <.menuconfig
-	if [ "$x" = "# $kernel_version" ]
-	then
-		rebuildsound=
-	fi
-fi
-
-if [ "$rebuildsound" ]
-then
-	# Activate the Linux compatible sound configuration.
-	# This may not work for all sound cards.  (See sound docs)
-	#
-	make -C drivers/sound mkscript kernelconfig >>.menuconfig.log 2>&1
-
-	echo "# $kernel_version" >.menuconfig
-fi
+echo -n "Preparing configuration scripts: version" 
 
 # Load the functions used by the config.in files.
+echo -n ", functions"
 load_functions
+
+if [ ! -e $CONFIG_IN ]
+then
+	echo "Your main config.in file ($CONFIG_IN) does not exist"
+	exit 1
+fi
+
+if [ ! -x $DIALOG ]
+then
+	echo "Your lxdialog utility does not exist"
+	exit 1
+fi
 
 #
 # Read config.in files and parse them into one shell function per menu.
 #
+echo -n ", parsing"
 parse_config_files $CONFIG_IN
 
+echo "done."
 #
 # Start the ball rolling from the top.
 #
@@ -1245,27 +1290,12 @@ cleanup1
 #
 if $DIALOG --backtitle "$backtitle" \
 	   --yesno "Do you wish to save your new kernel configuration?" 5 60
-	   
 then
 	save_configuration
-	stty $S_TERMIO
-	clear
-
-	cat <<EOM
-
-
-The linux kernel is now hopefully configured for your setup.
-Check the top-level Makefile for additional configuration,
-and do a 'make dep ; make clean' if you want to be sure all
-the files are correctly re-made.
-
-EOM
+	echo
+	echo The linux kernel is now configured for your setup.
 else
-	clear
-	stty $S_TERMIO
-	echo -e "Your kernel configuration changes were NOT saved.\n"
+    	echo 
+	echo Your kernel configuration changes were NOT saved.
 fi
-
-
 exit 0
-
